### ISSUE TITLE
Can you provide image sequences?

### ISSUE THREAD

**Issue by HWP97** [kangpeilun/VastGaussian#12]
Hi, thank you for your great work!

I'm trying to reproduce your results.
However, I have some problems in training.
I downloaded the scene residence and unzipped it.
It has image files like A/DJI_0413.JPG ...... 
But dataset reader requires image file formats like images/000330.jpg

can you provide image sequences for training?

**Comment by kangpeilun** [comment]
You can first test on Mill19 dataset, https://vastgaussian.github.io/ has data after pretreatment

**Comment by HWP97** [comment]
Do you mean this repository cannot train in Urbanscene3D dataset for now?

**Comment by kangpeilun** [comment]
Yep, the current progress is to test and write the code on a small dataset like train, and then resolve the RAM and VRAM overflow issues on a dataset like Mill-19, and not yet to test Urban However, you can refer to the pre-processed data provided by the official, such as residence/images.bin, to get which pictures need to be trained

**Comment by HWP97** [comment]
Thank you for quick response!
I'll download this Mill-19 dataset thank you!
