### ISSUE TITLE
loading cameras occupies too much ram？

### ISSUE THREAD

**Issue by Livioni** [kangpeilun/VastGaussian#6]
I got stuck at this step when I first loaded the Rubble dataset, which took up 100+G of RAM. I'm wondering if I did the right thing.

I set resolution = 4

https://github.com/kangpeilun/VastGaussian/blob/2d03641643fcc23e78557d543b1fa9b09e901e0a/scene/datasets.py#L82C1-L88C81

``` python
        for resolution_scale in resolution_scales:
            print("Loading Training Cameras")
            self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale,
                                                                            args)
            print("Loading Test Cameras")
            self.test_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.test_cameras, resolution_scale,
                                                                           args)
```

**Comment by ZhangZhan-YC** [comment]
There are too many cameras in the MILL_19 datasets,(1940 imgaes).So i think partition should be done befor the cameraList_from_camInfos().

**Comment by Livioni** [comment]
> There are too many cameras in the MILL_19 datasets,(1940 imgaes).So i think partition should be done befor the cameraList_from_camInfos().

I'm trying to load the minimum data to do the split and see if it works on my 128G RAM server.

**Comment by Livioni** [comment]
I added a separate [script](https://github.com/kangpeilun/VastGaussian/blob/2d2e1f7640129377f1ae5e28842b3ff9503b71d3/partitioning.py) to perform the partitioning operation that only needs to load the point cloud data and camera data.  #10
